# Generated by Django 4.2 on 2023-05-30 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.AddField(
            model_name='cartlist',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
