# Generated by Django 4.2 on 2023-05-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_items_user_cartlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
