# Generated by Django 4.2 on 2023-06-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_payment_alter_checkout_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
