# Generated by Django 4.2 on 2023-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_categ_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
